version: '3.8'

# Docker Compose for Prowler Dashboard
# Pulls and builds from: https://github.com/pranavanil47/prowlerdash

services:
  postgres:
    image: postgres:15-alpine
    container_name: prowler-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-prowler_db}
      POSTGRES_USER: ${POSTGRES_USER:-prowler_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prowler_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prowler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-prowler_user} -d ${POSTGRES_DB:-prowler_db}"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: https://github.com/pranavanil47/prowlerdash.git
      dockerfile: Dockerfile
    container_name: prowler-app
    depends_on:
      postgres:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT:-5000}
      NODE_ENV: ${NODE_ENV:-production}
      TRUST_PROXY: "true"
      COOKIE_SECURE: "false"
    expose:
      - "5000"
    networks:
      - prowler-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Database initialization service
  db-setup:
    image: postgres:15-alpine
    container_name: prowler-db-setup
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD:-prowler_password}
    networks:
      - prowler-network
    command: >
      sh -c "
        echo 'Setting up database extensions and permissions...' &&
        psql -h postgres -U ${POSTGRES_USER:-prowler_user} -d ${POSTGRES_DB:-prowler_db} -c \"
          CREATE EXTENSION IF NOT EXISTS \\\"uuid-ossp\\\";
          GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB:-prowler_db} TO ${POSTGRES_USER:-prowler_user};
          GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${POSTGRES_USER:-prowler_user};
          GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_USER:-prowler_user};
          GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${POSTGRES_USER:-prowler_user};
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRES_USER:-prowler_user};
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_USER:-prowler_user};
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${POSTGRES_USER:-prowler_user};
        \" &&
        echo 'Database setup completed successfully!'
      "
    restart: "no"

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: prowler-nginx
    depends_on:
      app:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_logs:/var/log/nginx
    networks:
      - prowler-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: >
      sh -c "
        if [ ! -f /etc/nginx/certs/cert.pem ]; then
          echo 'Generating SSL certificates...'
          apk add --no-cache openssl
          mkdir -p /etc/nginx/certs
          openssl genrsa -out /etc/nginx/certs/key.pem 2048
          openssl req -new -key /etc/nginx/certs/key.pem -out /etc/nginx/certs/cert.csr -subj '/C=US/ST=State/L=City/O=Organization/CN=localhost'
          openssl x509 -req -in /etc/nginx/certs/cert.csr -signkey /etc/nginx/certs/key.pem -out /etc/nginx/certs/cert.pem -days 365
          rm /etc/nginx/certs/cert.csr
          echo 'SSL certificates generated successfully!'
        fi
        nginx -g 'daemon off;'
      "

  # Admin user creation service (runs after app is up)
  create-admin:
    build:
      context: https://github.com/pranavanil47/prowlerdash.git
      dockerfile: Dockerfile
    container_name: prowler-create-admin
    depends_on:
      app:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      TRUST_PROXY: "true"
      COOKIE_SECURE: "false"
    networks:
      - prowler-network
    command: >
      sh -c "
        echo 'Waiting for application to be fully ready...' &&
        sleep 10 &&
        echo 'Creating default admin user...' &&
        node -e \"
          import bcrypt from 'bcrypt';
          import { storage } from './server/storage.js';
          
          async function createAdmin() {
            try {
              const existing = await storage.getUserByEmail('admin@email.com');
              if (existing) {
                console.log('Admin user already exists');
                return;
              }
              
              const passwordHash = await bcrypt.hash('admin', 10);
              const user = await storage.createUser({
                email: 'admin@email.com',
                username: 'admin',
                passwordHash,
                role: 'admin',
                firstName: 'Admin',
                lastName: 'User'
              });
              console.log('Admin user created:', user.email);
            } catch (error) {
              console.error('Error creating admin:', error);
            }
            process.exit(0);
          }
          
          createAdmin();
        \" &&
        echo 'Admin user setup completed!'
      "
    restart: "no"

volumes:
  postgres_data:
    driver: local
  nginx_certs:
    driver: local
  nginx_logs:
    driver: local

networks:
  prowler-network:
    driver: bridge