version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: prowler-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-prowler_db}
      POSTGRES_USER: ${POSTGRES_USER:-prowler_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prowler_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prowler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-prowler_user} -d ${POSTGRES_DB:-prowler_db}"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      sh -c "
        echo 'CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";' > /docker-entrypoint-initdb.d/01-extensions.sql &&
        echo 'GRANT ALL PRIVILEGES ON DATABASE prowler_db TO prowler_user;' > /docker-entrypoint-initdb.d/02-permissions.sql &&
        docker-entrypoint.sh postgres
      "

  app:
    build:
      context: https://github.com/pranavanil47/prowlerdash.git
      dockerfile: Dockerfile
    container_name: prowler-app
    depends_on:
      postgres:
        condition: service_healthy
      db-setup:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT:-5000}
      NODE_ENV: ${NODE_ENV:-production}
      TRUST_PROXY: "true"
      COOKIE_SECURE: "false"
    ports:
      - "5000:5000"
    volumes:
      - app_logs:/app/logs
    networks:
      - prowler-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database initialization service
  db-setup:
    build:
      context: https://github.com/pranavanil47/prowlerdash.git
      dockerfile: Dockerfile
    container_name: prowler-db-setup
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - prowler-network
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 10 &&
        echo 'Initializing database schema and admin user...' &&
        node scripts/init-db.js &&
        echo 'Database initialization completed!'
      "
    restart: "no"

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  prowler-network:
    driver: bridge